; PlatformIO Project Configuration File
; FingerprintDoorbell v0.6 — Platform Update (Variant B, Step 1)

[env:esp32doit-devkit-v1]
platform = espressif32@6.9.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps = 
	mathieucarbou/ESPAsyncWebServer@3.4.5
	mathieucarbou/AsyncTCP@3.3.2
	ayushsharma82/ElegantOTA@3.1.6
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit Fingerprint Sensor Library@^2.1.0
	intrbiz/Crypto@^1.0.0

lib_ldf_mode = deep+
board_build.filesystem = spiffs
build_flags = 
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1

;build_flags = -D CUSTOM_GPIOS    ;uncomment for custom GPIO support
